### ISSUE TITLE
When there are multiple alternative methods of payment, I want to choose the order of payment.

### ISSUE THREAD

**Issue by stormcat664** [Card-Forge/forge#3668]
**Is your feature request related to a problem? Please describe.**
For example, when casting a Kerik with convoke, the current UI always pays convoke first, so tapping a black creature pays black mana, but I sometimes want to pay Phyrexian mana first with life and then pay the remaining generic mana with convoke.

**Describe the solution you'd like**
Display the Payment Method Selection window

**Describe alternatives you've considered**
It can handle other similar situations.

**Comment by Hanmac** [comment]
related to https://github.com/Card-Forge/forge/issues/309

in general we need to refactor that convoke is paid After Mana Abilities are activated

for Phyrexian Mana we need to make it that the user need to choose (over a dialog) how to pay for the ability/spell because this has changes how (cost less/more to cast) interact with it

also `K'rrik, Son of Yawgmoth` ability is in this regard different from Phyrexian mana because it should be on the same layer as Convoke (after Mana ability)

**Comment by Goddfrey** [comment]
Wouldn't it be possible to do everything at the same time? Player declare they cast a spell, then they can click on their life (if phyrexian mana), creatures (if convoke) or mana producing permanents in any order they choose, even mixed, like creature-land-creature. Would it require to change the current code too drastically? Or are MtG rules more strict than that?

**Comment by Hanmac** [comment]
This is the order by the rules:

* 601.2b checks how Hybrid/Phyrexian Mana is paid
* 601.2f changes how reduce Cost/raise Cost applies
* 601.2g If the total cost includes a mana payment, the player then has a chance to activate mana abilities (see rule 605, “Mana Abilities”). **Mana abilities must be activated before costs are paid.**
* 601.2h Costs are paid, this also where convoke and K'rrik's ability should be done

**Comment by stormcat664** [comment]
I noticed today that when I cast a multi-colored card with convoke, I get a choice of which color mana to allocate to it. Can't it be made to appear even when it is mono-colored and generic mana?

**Comment by Jetz72** [comment]
@tool4ever Was this resolved by #6700?

**Comment by tool4ever** [comment]
Hmn there have been multiple aspects raised here and some of the order is still not quite right I guess.
Though I couldn't say what this means for the original request of "Kerik with convoke".
But beyond that I don't really see this one offering any substantial information which isn't written clearer in the issue mentioned above, so for the sake of keeping the tracker cleaned up I'd still lean towards closing it 🤷‍♂
