### ISSUE TITLE
Forge could handle "xxxxxxx you control attack each combat if able"

### ISSUE THREAD

**Issue by dennisfriedrichsen** [Card-Forge/forge#8514]
**Is your feature request related to a problem? Please describe.**
Forge is *really* smart in a lot of ways.  It takes care of almost everything for you.  One thing it doesn't even try to do is something like "xxxxxxx you control attack each combat if able".  Right now, if you don't do the attack correctly, it just says "Attack declaration invalid" and then you go back and try again until you get it right.

**Describe the solution you'd like**
When I need to attack with all of my goblins each turn (due to an effect like Goblin Rabblemaster - "Other goblin creatures you control attack each combat if able"), Forge could just declare the attack.  Right now, if I *only* have goblins, it's each enough to do an Alpha Strike and then pull back 1 or two creatures.  But when I have a bunch of tokens and I want half to attack and half to NOT attack, that gets very tedious.

**Additional context**
OS: MacOS 16.5.1
Java: 21
Forge: 2.0.05

<img width="1800" height="1100" alt="Image" src="https://github.com/user-attachments/assets/492dbd6c-4b44-4b19-89c1-0efecafb5369" />

**Comment by Hanmac** [comment]
I think that was fixed a few days ago, you need to use newer snapshot

**Comment by dennisfriedrichsen** [comment]
> I think that was fixed a few days ago, you need to use newer snapshot

I'll retest with a current git and close if appropriate.

**Comment by dennisfriedrichsen** [comment]
Just tested with a current pull from master (6e6509eaff6dfa368990962abe871e6345f48ce9).  Still getting the "Attack declaration invalid".
