### ISSUE TITLE
New Android version 2.0.07-10.27 hangs on checking for update

### ISSUE THREAD

**Issue by Life-Saver666** [Card-Forge/forge#8975]
**Describe the bug**
Game doesn't start, stuck on "Checking for updates" screen.  swiping back displays animated logo, and game shuts down.

**To Reproduce**
1. Update
2. run, 
3. download assets
4. restart
5. gets stuck there.

Tried closing and clearing cache, same problem.
Tried re downloading and installing(update)

**Expected behavior**
Should automatically bring the main menu

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/338e6d5e-fdce-487a-b4c4-236b75a43817" />

**Smartphone (please complete the following information):**
 - Device: Moto G stylus 5G 2023
 - OS: Android
 - Version 14

**Comment by TheNaturalCauses** [comment]
Also experiencing this bug.
Device: pixel pro 11 pro
Os: android
Version: latest

**Comment by Hanmac** [comment]
Known issue:
https://github.com/Card-Forge/forge/pull/8849#issuecomment-3430841392

@Jetz72 is probably working on it

**Comment by Life-Saver666** [comment]
Issue still persist, same with 10.22

**Comment by Life-Saver666** [comment]
Also, it's possible It was caused in an earlier version, I didn't update for a few days.

**Comment by Hanmac** [comment]
@Life-Saver666 update new forge.log to fix the issue

**Comment by Jetz72** [comment]
Should be fixed for real this time by #8978.

**Comment by Hanmac** [comment]
@Jetz72 i still get some issue, but i need to debug that at home

**Comment by Life-Saver666** [comment]
> [@Life-Saver666](https://github.com/Life-Saver666) update new forge.log to fix the issue

How do I do that? I just download the APK file, my phone isn't rooted, I can't access the installed folder.

**Comment by Jetz72** [comment]
I think he meant to say Forge snapshot rather than forge.log. Updating to the latest snapshot should resolve things now.

**Comment by Life-Saver666** [comment]
> I think he meant to say Forge snapshot rather than forge.log. Updating to the latest snapshot should resolve things now.

Thanks, I didn't notice it was updated as it was still the same version.   It's working now!   Thanks for the dedication to this great game app.
