### ISSUE TITLE
New Game+ broken

### ISSUE THREAD

**Issue by vulmen** [Card-Forge/forge#9286]
**Describe the bug**
A while back I started New Game+ and disabled the main quest. After playing and collecting cards for a long while; I attempted to start New Game+ again and do the main quest. It appears the flag to skip the main quest is stuck active and does not get reset...because the mage will not speak to me and the portal will not activate when selecting to enable the main quest.

**To Reproduce**
1. New game
2. New game+ choosing to disable the main quest
3. New game+ but choosing to play the main quest

**Expected behavior**
Enable the main quest, speak with the mage and open the portal.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I've found there are no workarounds available to the player. No savegame editing, no console commands allowed, no export/import bypass. Without a bugfix, my save file is permanently locked out of the main quest.

**Comment by Jetz72** [comment]
Should be fixed by #9295. Redownload the daily snapshot and try starting NG+ again.

**Comment by vulmen** [comment]
It still doesn't reset the main quest - perhaps I have a unique issue. I waited to test this after another patch came out just to be sure but the results have not changed. On New Game+ when activating the main quest, the mage still only has the "Bye" option.

I'll attach my save file so the New Game+ can be tested. It may help to see if there's something I messed up somehow.

[forge.zip](https://github.com/user-attachments/files/24058348/forge.zip)

**Comment by EfourC** [comment]
I just tried doing a New Game+ and choosing to activate the tutorial + main quest and hit the same problem where the game is soft-locked.

The exit portal doesn't work and the intro mage is stuck with only a single line of dialogue saying "Hello, planeswalker <name>.", with my only reply option being "Goodbye".

This was on a fresh clone of the master branch on Jan 9, 2026 (has up to commit 2b850693e73b5fd9ff346d14dea4f8cfae492332).

**Comment by magaruis** [comment]
Issue still exists in the latest version.  Ran into it myself.  Don't know if there is some quick flag I can change somewhere while waiting for a fix ? 

*Edit* ; For those running into this problem , an easy workaround is starting the game and giving yourself the apprioriate quest with the console command (F9 , give quest <id>).  You will have to figure out your questID in some way.  I lucked out and managed to find the exact moment I started a new game+ (52 is the start of the  quests to find the different castles).  

You can manually start the quest with the console command give quest 43

**Comment by Blackvipe99** [comment]
Root cause found and fixed in #11886: New Game+ cleared the quests and quest flags but not the `noQuest` **character** flag that the "skip the main quest" choice sets, and the mage's "Why am I here?" option requires it unset. For a save that's already stuck, once that lands you can run `resetQuests` in the F9 console and talk to the mage again (no need for another New Game+).
